[package]
name = "stark_dca"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.2"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.52.0" }

[[target.starknet-contract]]
sierra = true
casm = true
